### ISSUE TITLE
All the feeds are dead

### ISSUE THREAD

**Issue by cannedDiarrhea** [h8pewou/legacy-webos-feeds#1]
Every single feed is dead and gives a "403 Forbidden" page. Is there a way you could find these feeds again elsewhere (maybe)? Thanks!

**Comment by h8pewou** [comment]
The feeds are up. It is meant to be accessed by Preware, on legacy webOS devices (e.g., Palm Pre or HP TouchPad). You can download the Packages.gz file to test their availability. As an example: [http://weboslives.eu/feeds/precentral/Packages.gz](http://weboslives.eu/feeds/precentral/Packages.gz).

**Comment by cannedDiarrhea** [comment]
my bad, i shoulda known considering i already have Preware. thank you though!
